# Generated by Django 4.0.4 on 2022-04-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject_area',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
