# Generated by Django 4.0.4 on 2022-04-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring_app', '0002_student_subject_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mentor',
            name='current_year',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
